sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t pgsdeepak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pgsdeepak/docker-react npm run test
